language: ruby
dist: xenial
sudo: false
cache: bundler
rvm:
  #- 2.7.1
  - 2.6.6
  - 2.5.8
  #- ruby-head
gemfile:
  - gemfiles/Gemfile-rails.5.0.x
  - gemfiles/Gemfile-rails.5.1.x
  - gemfiles/Gemfile-rails.5.2.x
  - gemfiles/Gemfile-rails.5.2.x-cukes-4
  - gemfiles/Gemfile-rails.5.2.x-cukes-5
  - gemfiles/Gemfile-rails.6.0.x
  - gemfiles/Gemfile-rails.6.0.x-cukes-5
  #- gemfiles/Gemfile-rails.edge
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.7.1
    - gemfile: gemfiles/Gemfile-rails.edge
    - gemfile: gemfiles/Gemfile-rails.5.2.x-cukes-5
    - gemfile: gemfiles/Gemfile-rails.6.0.x-cukes-5
  fast_finish: true

script: bundle exec rspec -f progress --force-color --color --tty

gemfile:
  - gemfiles/cucumber1.gemfile
  - gemfiles/cucumber2.gemfile
  - gemfiles/cucumber3.gemfile
  - gemfiles/cucumber4.gemfile
