language: ruby
dist: xenial
cache: bundler
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - 2.4.10
  - 2.3.8
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

script:
  - gem install bundler
  - bundle exec rake spec
  - bundle exec rake cucumber
