language: ruby
dist: xenial
cache: bundler
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
matrix:
  allow_failures:
    - rvm: 2.1.10
  fast_finish: true

script:
  - bundle exec rake spec
  - bundle exec rake cucumber
